const pumpIndexList = [
    {
        "ID": "1",
        "PD": "0",
        "caption": "Franklin Electrics SS-Series submersible pump utilises high grade stainless steel materials for the most demanding applications.",
        "img": "fps_ss_series.png",
        "range": "FPS-SS",
        "subtitle": "Stainless Steel Submersible Pumps",
        "title": "FPS SS Series",
        "var1": "Heads up to 400m|Flow rates up to 300m³/h",
        "var1n": "Performance",
        "var2": "Residential|Commercial|Agricultural|Mining|Marine|Municiple|Industrial|River water extraction|DWAF",
        "var2n": "Applications",
        "var3": "Stainless steel impellers and diffusers to resist corrosion|Suited to operate in horizontal position|Built-in check valve to protect the pump against water hammer|Energy efficient hydraulic design for cost-effective operation|Maximum alloable solid quantity = 50g/m³|Solid dimension: maximum 2mm|Cast motor bracket",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "2",
        "PD": "0",
        "caption": "The FS series pumps have been engineered in all AISI 316 stainless steel for efficient and reliable pumping of liquids in extreme environments.",
        "img": "fps_fs_series.png",
        "range": "FPS-FS",
        "subtitle": "316 stainless steel submersible pumps",
        "title": "FPS FS Series",
        "var1": "8\": 100 and 130 m³/h|10\": 180 and 200 m³/h|12\": 260, 300 and 400 m³/h.",
        "var1n": "Performance",
        "var2": "Residential|Commercial|Agricultural|Mining|Marine|Municiple|Industrial|River water extraction|DWAF",
        "var2n": "Applications",
        "var3": "100% factory tested|Stainless steel AISI 316 bowls - investment cast|8”, 10” and 12” sizes|Stainless steel impellers and diffusers|llers locked onto shaft with keys|Rubber bearings|Integrated non-return valve on all models|Stainless steel 329 duplex shaft for increased durability|All pumps suit Franklin Electric motors|Flanged and BSPP discharges|Maximum running time at zero delivery is 2 minutes.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "3",
        "PD": "0",
        "caption": "The SubDrive solar pumping system uses existing Franklin Electric components to produce a rugged, high-output system for use in remote and harsh environments.",
        "img": "subdrive_solar.png",
        "range": "SUBDIVE SOLAR",
        "subtitle": "Solar Pumping System",
        "title": "SubDrive Solar",
        "var1": "Variety of flow rates available: 30, 45, 70, 150 and 270 ℓ/min",
        "var1n": "Performance",
        "var2": "Livestock Watering|Game Farms|Rural Water Supplies|Irrigation Systems|Water from Borehole, Rivers and Dams",
        "var2n": "Applications",
        "var3": "High flow system|Proven motor and pump technology and reliability|Built-in diagnostics and protection.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "4",
        "PD": "0",
        "caption": "Franklin Electrics SVM submersible borehole pumps are high quality, efficient and readily available at a competitive price. The use of different material for the internal components eliminates the possibility of the pump seizing, ensuring the long-term operation of the pump.",
        "img": "svm_borehole_pump.png",
        "range": "SVM",
        "subtitle": "Submersible Pump",
        "title": "SVM Borehole Pump",
        "var1": "Flow rates from 30-400 ℓ/min|Heads up to 290 m.",
        "var1n": "Performance",
        "var2": "Residential|Commercial|Agricultural|Mining|Marine|Municiple|Industrial|River water extraction|DWAF",
        "var2n": "Applications",
        "var3": "Stainless steel motor adaptor and discharge head|Polycarbonate impellers, stainless steel bowls and Noryl diffusers|Built-in check valve to protect the pump against water hammer|Impeller design incorporates built-in up-thrust protection.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "5",
        "PD": "0",
        "caption": "Franklin Electrics SE and SM high efficiency end suction pumps with investment cast impellers.",
        "img": "fps_s_series_industrial.png",
        "range": "FPS-S",
        "subtitle": "FPS S-Series SE and SM High Efficiency Industrial Pumps",
        "title": "FPS S-Series Industrial Pumps",
        "var1": "Heads of up to 155 m|Flow rates of up to 1300 m³/h",
        "var1n": "Performance",
        "var2": "Air-conditioning|Light industry|Cooling tower",
        "var2n": "Applications",
        "var3": "Back pull-out design for reduced downtime|Replaceable neck rings on front and rear of the impeller for easy and cost-effective maintenance and continued high efficieny|Shaft material - AISI 420 stainless steel for high resistance against oxidation|Cooling fins on the bearing frame to remove heat from the oil - extended bearing life|Magnetic filter in drain plug - no fines in the oil|Impellers in 304 and/or 201 stainless steel|All impellers are investment cast for optimal efficiency|Patented “Twinner System” for easy gland servicing.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "SE & SM"
    },
    {
        "ID": "6",
        "PD": "0",
        "caption": "Franklin Electrics SF high efficiency end suction pumps with investment cast impellers.\t",
        "img": "fps_s_series_agricultural.png",
        "range": "FPS-S",
        "subtitle": "SF high efficiency agricultural pumps",
        "title": "FPS S-Series Agricultural Pumps",
        "var1": "Heads of up to 100m|Flow rates of up to 600m³/h",
        "var1n": "Performance",
        "var2": "Agriculture / irrigation|River water extraction|DWAF\n",
        "var2n": "Applications",
        "var3": "Replaceable neck rings on front and rear of the impeller for easy and cost-effective maintenance and continued high efficieny|Shaft material - AISI 420 stainless steel for high resistance against oxidation|Cooling fins on the bearing frame to remove heat from the oil - extended bearing life|Magnetic filter in drain plug - no fines in the oil|Impellers in 304 and/or 201 stainless steel|All impellers are investment cast for optimal efficiency|Patented “Twinner System” for easy gland servicing.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "SF"
    },
    {
        "ID": "7",
        "PD": "0",
        "caption": "SK series high pressure multi-stage pumps are investment cast for reduced friction and increased efficiency.",
        "img": "fps_s_series_multistage.png",
        "range": "FPS-S",
        "subtitle": "SK high pressure horizontal multi-stage pumps",
        "title": "FPS S-Series Mutli-Stage Pumps",
        "var1": "Heads of up to 200m|Flow rates up to 300m³/h",
        "var1n": "Performance",
        "var2": "Agriculture / irrigation|River water extraction / water supply|DWAF / general industry\t",
        "var2n": "Applications",
        "var3": "Replaceable neck rings on front and rear of the impeller for easy and cost-effective maintenance and continued high efficiency|Shaft material - carbon steel\nCooling fins on the bearing frame to remove heat from the oil - extended bearing life|Magnetic filter in drain plug - no fines in the oil|Impellers in cast iron or bronze|All impellers are investment cast for optimal efficiency|Patented “Twinner System” for easy gland servicing.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "SK"
    },
    {
        "ID": "8",
        "PD": "0",
        "caption": "Franklin Electrics 100 mm, 150 mm & 200 mm encapsulated motors are manufactured to ISO 9001 standards, and are the quality drive for submersible pumps, offering a maintenance-free long-life submersible motor operation.",
        "img": "encapsualted_submersible.png",
        "range": "ESM",
        "subtitle": "Franklin Electric Encapsulated Submersible Motors",
        "title": "Encapsulated Submersible Motor",
        "var1": "Residential|Commercial|Agricultural|Mining|Marine|Municiple|Industrial|River water extraction|DWAF",
        "var1n": "Applications",
        "var2": "Water lubricated thrust|Radial bearings|Sand Fighter seal system (150 mm and 200 mm) for sandy applications|High efficiency electrical design.",
        "var2n": "Features",
        "var3": "Hermetically sealed stator, anti track, self healing stator resin prevents motor burn out|37 and 45 kW Motors up to 50 °C ambient temperature|Removable “Water Bloc” lead connector|Cable material according to drinking water regulations (VDE / ACS / KTW approved)|Sand fighter® Motor with SiC-Mechanical Seal|High efficiency electrical design for low operation cost|All motors prefilled and 100% tested|Max. storage temperature -15 °C - + 60 °C|Non contaminating FES91 -filled design|45 kN High Thrust Versions",
        "var3n": "Specifications",
        "var4": "4 - 45 kW|6\" NEMA flange|Protection: IP 68|Starts per hour: max. 20|Installation: vertical/horizontal|Standard Voltage: 380-415 V/50 Hz, 460 V/60 Hz|Voltage tolerance 50 Hz: -10% / +6% UN [380-415 V = (380-10%) – (415+6%)]|Voltage tolerance 60 Hz: ±10% UN|Motor protection: Select thermal overloads according to DIN 61947-4-1|Insulation: Class F|Rated ambient temperature: 4- 30 kW up to 30 °C; 37 & 45 kW up to 50 °C|Cooling flow: min. 0,16 m/s|Motor lead in 4m length (VDE / ACS / KTW approved)",
        "var4n": "Technical Specifications",
        "var5": "Other voltages|YΔ - start (pos. of cables 90°)|45 kN High Thrust Version (Standard in 37 / 45 kW Motors)|Motors complete in 304 SS and in complete 316 SS|PT 100 temperature sensor (sold separately)|Special Lead lengths up to 50 m|Built-in PTC temperature sensor|Built-in SubMonitor Transmitter (standard for 37 & 45 kW)",
        "var5n": "Options",
        "variation": ""
    },
    {
        "ID": "9",
        "PD": "1",
        "caption": "Franklin Electrics range of J-Class Sandhandler submersible pumps feature the TRI-SEAL floating stage system that improves efficiency, protects against wear when pumping abrasives such as sand, and reduces running costs.",
        "img": "j_class_sandhandler.png",
        "range": "J-CLASS",
        "subtitle": "Submersible Pump",
        "title": "J-Class Sandhandler",
        "var1": "Available in seven performance ranges: 20, 30, 40, 70, 90, 150 and 200 ℓ/min.",
        "var1n": "Performance",
        "var2": "Residential|Commercial|Agricultural|Mining|Marine|Municiple|Industrial|River water extraction|DWAF",
        "var2n": "Applications",
        "var3": "Provide high performance in the harshest conditions|Stainless steel hub floats|Celcon impeller|Noryl diffuser and disc|Floating stage design|Ceramic shaft sleeve and rubber discharge bearing protect shaft and eliminates sand wear.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "10",
        "PD": "0",
        "caption": "SVM pressure sets work in conjunction with high efficiency stainless steel pumps, incorporating EPDM food grade bladders best suited for the transportation of pressurised drinking water.",
        "img": "svm_pressure_sets.png",
        "range": "SVM",
        "subtitle": "SVM pressure sets",
        "title": "SVM Pressure Sets",
        "var1": "Flow rates from 30ℓ/min to 400ℓ/min|Heads up to 290m.",
        "var1n": "Performance",
        "var2": "Automatic distribution of pressurised water for domestic purposes|Increase pressure of mains supply|Garden watering – automatic irrigation|Pressure distribution of water from wells and storage tanks|Washing systems",
        "var2n": "Applications",
        "var3": "Stainless steel motor adaptor and discharge head for increased strength and durability|Polycarbonate impellers, stainless steel bowls and Noryl® diffusers reduce possibility of seizing|Built-in check valve to protect the pump against water hammer|Impeller design incorporates built-in up-thrust protection|Features an 11mm across flats shaft.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "11",
        "PD": "0",
        "caption": "Franklin Electrics stainless steel, high performance horizontal multi-stage pumps are designed for use in domestic, industrial and agricultural applications.",
        "img": "fps_mh.png",
        "range": "FPS-MH",
        "subtitle": "Horizontal multi-stage pumps",
        "title": "FPS MH Series",
        "var1": "Small domestic and industrial systems / domestic water supply|Water distribution / pressure boosting|Irrigation / gardening / sprinklers / rainwater collection|Industrial plants / wash down units|Cooling and chilling / heating and conditioning / air conditioning systems|Fertigation|Other various installations.",
        "var1n": "Applications",
        "var2": "Compact close-coupled design, robust and rust-resistant / superior efficiency and performance|Flexible application base plate|Floating neck ring in AISI 304 and PTFE, Teflon|Heavy duty oversized motor shaft|Impellers and diffusers are made of stainless steel for durability|Easy maintenance|Hydraulic stack can be removed without disconnecting the pipework|Strong and leak-proof motor bearing in the motor bracket|Pumping of clear fluids|Mechanical seal SC/SC/Viton.",
        "var2n": "Features",
        "var3": "",
        "var3n": "",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "12",
        "PD": "0",
        "caption": "Franklin Electrics stainless steel vertical multi-stage pumps are designed for use over a wide variety of applications.",
        "img": "fps_vr.png",
        "range": "FPS-VR",
        "subtitle": "Stainless Steel Vertival Multi-stage Pumps",
        "title": "FPS VR Series",
        "var1": "Capacities up to 26m³/h|Heads up to 25 bar",
        "var1n": "Performance",
        "var2": "Mining|Pressure boosting|Boiler feed|Water supply and treatment|Reverse osmosis|Wash down units|Hot/cold water circulation for HVAC systems|Irrigation",
        "var2n": "Applications",
        "var3": "All stainless steel hydraulics for superior durability, efficiency, and performance over a wide variety of applications|Rugged motor mounting with oversized ball bearings ensure long operating life in the toughest jobs. Heavy-duty motor bearing not required|Standard equipment mechanical seal provides superior sealing between pump end and motor|In-line suction and discharge with round flanges fit widest range of applications and provide convenient, compact installation|Rugged IEC mount electric motors with standard B14/B5 flanges.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "13",
        "PD": "1",
        "caption": "\nRobust and durable in their construction, these pumps are able to operate under the toughest conditions.",
        "img": "mono_bp.png",
        "range": "MONO",
        "subtitle": " ",
        "title": "Mono BP Range",
        "var1": "Pumping up to 100 000ℓ/h|Heads up to 300m.",
        "var1n": "Performance",
        "var2": "Residential|Commercial|Agricultural|Mining|Marine|Municiple|Industrial|River water extraction|DWAF\t",
        "var2n": "Applications",
        "var3": "5 Year Guarantee|New FE design offers improved performance and efficiency|Mono progressing cavity pumping technology proven for over 60 years|Long-life, fully machined flexible shafts with rolled threads eliminate the need for vulnerable universal coupling|Monostroom and monomeester discharge heads use sealed pre-greased bearings for optimum, maintenance-free operation|Precision-machined and threaded column pipes incorporating truncated threads for maximum strength|Twin datum bearings fitted to all larger pump elements to eliminate drive shaft stresses",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "BP"
    },
    {
        "ID": "14",
        "PD": "0",
        "caption": "Suitable for use on shallow boreholes, Mono hand pumps have served rural Africa since the 1960s.",
        "img": "mono_hand_pumps.png",
        "range": "MONO-H",
        "subtitle": " ",
        "title": "Mono Hand Pumps",
        "var1": "Flow rates up to 12ℓ/min|Depths up to 120m",
        "var1n": "Performance",
        "var2": "Stock watering|Rural drinking water supply|Filling of overhead tanks|Water abstraction where no alternative power source is available",
        "var2n": "Applications",
        "var3": "Efficient, robust design|Geared action makes it easy for even the young and infirm to draw water",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "15",
        "PD": "1",
        "caption": "Franklin Electrics range of horizontal discharge transfer pumps has been developed for a wide variety of high pressure water transfer applications. The modular construction affords ease of interchangeability of components.",
        "img": "mono_hd.png",
        "range": "MONO",
        "subtitle": " ",
        "title": "Mono HD Range",
        "var1": "Flow rates up to 60m³/h|Heads up to 450m",
        "var1n": "Performance",
        "var2": "Irrigation|Stock watering|Domestic water supply|Slurry pump gland service",
        "var2n": "Applications",
        "var3": "Steady, non-pulsating flow|Positive displacement pumping principle|Abrasion-resistant pumping element comprising a resilient rubber stator and a hard chrome-plated rotor|Inherently self-priming|Versatility - Mono HD pumps can be driven by electric motors, diesel or petrol engines, and tractor PTOs.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "HD"
    },
    {
        "ID": "16",
        "PD": "0",
        "caption": "The EZstrip™ is a revolutionary PC pump innovation, which can be \"Maintained-in-Place\", making a day-long maintenance operation a 30 minute job.",
        "img": "ezstrip.png",
        "range": "EZ",
        "subtitle": "Transfer Pump",
        "title": "EZstrip",
        "var1": "Flow rates up to 225 m³/h|Pressures up to 12 bar",
        "var1n": "Performance",
        "var2": "Domestic and Industrial effluents|Hydrated lime slurry|Sludge|Shear sensitive latex emulsion|Milk curds|Sauces|Fruit juices|Industrial chemicals and detergents|Starch slurries|Coating clays|Gypsum and silicate|Paper stocks|Agricultural slurries",
        "var2n": "Applications",
        "var3": "Quick and easy maintenance and unblocking|Requires only spanner and an allen key to maintain|Reduced maintenance downtime an labour savings|No need to disconnect suction and discharge pipework|Eliminates dismantling lengths",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "17",
        "PD": "0",
        "caption": "Franklin Electrics range of industrial pumps is designed for pumping viscous, abrasive and shear-sensitive products in various industrial applications.",
        "img": "mono_industrial_g_range.png",
        "range": "MONO",
        "subtitle": " ",
        "title": "Mono Industrial G Range",
        "var1": "Flow rates up to 230m³/h|Pressures up to 30 bar",
        "var1n": "Performance",
        "var2": "Mining|Water & waste|Pharmaceutical\nFood & beverage|Agriculture|Petrochemical|Pulp & paper",
        "var2n": "Applications",
        "var3": "Uniform, non-pulsating flow|Pressure independent of speed|Capacity proportional to speed|Low shear",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "G"
    },
    {
        "ID": "18",
        "PD": "0",
        "caption": "Franklin Electrics range of industrial pumps is designed for pumping viscous, abrasive and shear-sensitive products in various industrial applications.",
        "img": "mono_industrial_m_range.png",
        "range": "MONO",
        "subtitle": " ",
        "title": "Mono Industrial M Range",
        "var1": "Flow rates up to 60m³/h|Pressures up to 30 bar",
        "var1n": "Performance",
        "var2": "Mining|Water & waste|Pharmaceutical\nFood & beverage|Agriculture|Petrochemical|Pulp & paper",
        "var2n": "Applications",
        "var3": "Uniform, non-pulsating flow|Pressure independent of speed|Capacity proportional to speed|Low shear",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "M"
    },
    {
        "ID": "19",
        "PD": "1",
        "caption": "Franklin Electrics Orbit GW range of pumps offers reliable performance over a broad range of heads and speeds. The abrasion-resistant pump also features low noise and vibration levels.",
        "img": "orbit_gw.png",
        "range": "ORBIT",
        "subtitle": " ",
        "title": "Orbit GW Range",
        "var1": "Flow rates up to 100m³/h|Heads up to 300m",
        "var1n": "Performance",
        "var2": "Residential|Commercial|Agricultural|Mining|Marine|Municiple|Industrial|River water extraction|DWAF",
        "var2n": "Applications",
        "var3": "5 Year Guarantee|New FE design offers improved performance and efficiency|Helical rotor technology|Flow is proportional to speed|Constant non-pulsating flow|High developed head allows irrigation directly from borehole|Stainless steel flexible shaft and bearing pieces|Rubber stabilisers centralise pump and columns firmly in the borehole|Pressure head developed is independant of pump speed|Abrasion-resistant|High load capability and angular contact thrust bearings in discharge head allow for pump setting depths of up to 300m|Discharge head suitable for drive by electric motor (AC/DC/solar), petrol or diesel engine, tractor or rotary windmill|High tensile drive shafts with rolled threads|Stainless steel, precision-ground flexible shaft|Stainless steel bearing pieces|Truncated parallel threads on pump and columns ensure high strength with perfect fit and alignment|Rubber stabilisers centralise pump and columns firmly in the borehole, eliminating noise and vibration|Can be installed on an incline or riverbank",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "GW"
    },
    {
        "ID": "20",
        "PD": "0",
        "caption": "Franklin Electrics Orbit hand pumps are easy to use and are ideal for rural water supply. The rugged, reliable, long-life design delivers a pump that is suitable for use in remote villages and similar environments.",
        "img": "orbit_hop.png",
        "range": "ORBIT HOP",
        "subtitle": " ",
        "title": "Orbit HOP Range",
        "var1": "HOP 4: high head / low flow|HOP 10: low head / high flow",
        "var1n": "Performance",
        "var2": "Stock watering|Rural drinking water supply|Filling of overhead tanks|Water abstraction where no alternative power source is available",
        "var2n": "Applications",
        "var3": "High quality anti-reversing bearing|Mechanical seal for filling overhead tanks|Stainless steel main shaft in discharge head|Automatic shaft setting – no shaft protrusion above discharge head|Quick and easy removal of handle or bearing assembly without affecting pump adjustment – lifting tackle is not required|Rugged, reliable, long-life design for low maintenance environment|Flow rate is proportional to speed|Bearings sealed for life.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "21",
        "PD": "1",
        "caption": "Franklin Electrics Orbit range of helical rotor, horizontal power pumps for high flow and high head water transfer duties and similar applications are highly efficient over a broad range of heads and speeds for reduced fuel and/or electricity consumption.",
        "img": "orbit_power_pump.png",
        "range": "ORBIT",
        "subtitle": " ",
        "title": "Orbit Power Pump Range",
        "var1": "Flow rates up to 70m³/h|Heads up to 300m",
        "var1n": "Performance",
        "var2": "Stock watering|Spray irrigation|Domestic water supply|Water extraction from saturated river beds|High capacity flow water transfer",
        "var2n": "Applications",
        "var3": "Abrasion-resistant|Constant, non-pulsating flow|Pressure head developed is independent of pump speed|Flow is proportional to speed|High developed head for irrigation|Suitable for drive by electric motor (AC/DC/solar), petrol engine, diesel engine or tractor PTO|Serviceable on site by unskilled labour|Stainless steel flexible shaft",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "POWER"
    },
    {
        "ID": "22",
        "PD": "0",
        "caption": "Franklin Electrics industrial helical rotor pumps offer excellent suction capabilities across a broad range of applications, from water and wastewater to mining and chemicals.",
        "img": "orbit_mini.png",
        "range": "ORBIT",
        "subtitle": " ",
        "title": "Orbit Mini Range",
        "var1": "Flow rates up to 160m³/h|Pressures up to 80 bar",
        "var1n": "Performance",
        "var2": "Agriculture|Brewing & beverages|Building & construction|Ceramics|Chemicals|Mining|Paper & pulp|Pharmaceuticals & cosmetics|Water & wastewater industry",
        "var2n": "Applications",
        "var3": "Excellent suction capabilities - inherently self-priming|Good solids handling capabilities including fibrous materials|Reversible - pumps in either direction with equal efficiency|Capacity is proportional to speed|Pressure is independent of speed|No valves|Loose seal/gland arrangement|Gentle handling of shear-sensitive products|Ability to handle viscous products of over 1-million centipoise|Solid or hollow shaft option|Pulse-free flow|Simple and robust construction|Ability to handle products with a large percentage of entrained gas.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "MINI"
    },
    {
        "ID": "23",
        "PD": "0",
        "caption": "Franklin Electrics industrial helical rotor pumps offer excellent suction capabilities across a broad range of applications, from water and wastewater to mining and chemicals.",
        "img": "mono_industrial_b_d.png",
        "range": "ORBIT",
        "subtitle": " ",
        "title": "Orbit Industrial B & D Range",
        "var1": "Flow rates up to 160m³/h|Pressures up to 80 bar",
        "var1n": "Performance",
        "var2": "Agriculture|Brewing & beverages|Building & construction|Ceramics|Chemicals|Mining|Paper & pulp|Pharmaceuticals & cosmetics|Water & wastewater industry",
        "var2n": "Applications",
        "var3": "Excellent suction capabilities - inherently self-priming|Good solids handling capabilities including fibrous materials|Reversible - pumps in either direction with equal efficiency|Capacity is proportional to speed|Pressure is independent of speed|No valves|Loose seal/gland arrangement|Gentle handling of shear-sensitive products|Ability to handle viscous products of over 1-million centipoise|Solid or hollow shaft option|Pulse-free flow|Simple and robust construction|Ability to handle products with a large percentage of entrained gas.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": "B & D"
    },
    {
        "ID": "24",
        "PD": "0",
        "caption": "Rotorflo is a high-performance, compact pump requiring little maintenance, designed for hygiene-conscious industries. Franklin Electric is the only South African pump manufacturer to be awarded the European Hygienic Equipment Design Group (EHEDG) certification for its design of a rotary lobe pump.",
        "img": "rotorflo.png",
        "range": "ROTORFLO",
        "subtitle": "Rotary Lobe Pumps",
        "title": "Rotorflo",
        "var1": "Flow rates up to 96m³/h|Pressures up to 15 bar",
        "var1n": "Performance",
        "var2": "Food|Pharmaceutical|Dairy|Hygiene-sensitive applications|For pumping shear-sensitive or viscous fluids",
        "var2n": "Applications",
        "var3": "Shafts are made of heavy-duty, large-sectioned stainless steel for less deflection and enhanced rigidity|Helical gears time the main and lay shafts to maintain accurate clearances between the rotors. These clearances ensure high volumetric efficiency and increased suction|Main bearings are of the standard taper-roller type|Gearboxes are grease or oil lubricated|Shaft sealing can be achieved by mechanical seal, packed gland or “O” ring, to suit application|The spigotted rotor case is positively located on the bearing housing, eliminating loose dowels|The 12-involute spline configuration ensures accurate positioning of rotors during assembly|Low-shear characteristics protect delicate products|Positive displacement technology ensures efficient transfer of all liquid viscosities|The pumping chamber is fully swept, ensuring no product entrapment|“O” ring seal profiled to the edge of pumping chamber. Most covers are flush, minimising areas where bacterial growth can occur|All wetted parts are made from 316 stainless steel|Full diameter porting supplied as standard. Fittings available to suit customer specification. Enlarged inlets for hopper feed also available|Shimming external to gearbox to allow for quick and simple adjustments of rotor clearances when required|The gear housing is manufactured from robust cast iron\nKeyed gears produce a positive drive to ensure that timing does not have to be reset when rotors are changed|“O” ring seals on rotor keeps splines free of product contamination|The front cover can be supplied with a pressure relief valve built in to protect against overload.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "25",
        "PD": "0",
        "caption": "Franklin Electrics Tsunami axial flow pumps are engineered and designed to move large volumes of water at relatively low heads.",
        "img": "tsunami.png",
        "range": "TSUNAMI",
        "subtitle": "Axial Flow Pumps",
        "title": "Tsunami",
        "var1": "Flow rates up to 2 600ℓ/s|Heads range from 1 to 100m",
        "var1n": "Performance",
        "var2": "Transfer of large volumes of water at relatively low levels|Aqua-culture and other marine industries|Effuent recycling within sewage works|Features in water parks|Backwash water from filters|Water harvesting from rivers and dams|Product transfer in process plants|Flood irrigation",
        "var2n": "Applications",
        "var3": "Low cost installation with minimal civil requirements|Permanently submerged turbine|Motor can be positioned well above the flood level|No valves or return valves required|Self-flushing|High efficiencies|Low load starting conditions|Varying head conditions result in small variations in flow|Range of materials of construction to suit various conditions|Heavy duty thrust assembly coupled with a Hardy Spicer shaft or a right-angled gear drive|Stainless steel shafts, impellers and impeller rings as standard materials of construction|Simple and reliable",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "26",
        "PD": "0",
        "caption": "A competitively priced progressing cavity pump, with a compact construction and maximum performance characteristics.",
        "img": "compact_c.png",
        "range": "COMPACT-C",
        "subtitle": " ",
        "title": "Compact C",
        "var1": "Flow rates up to 440 m³/hr|Pressures up to 24 bar",
        "var1n": "Performance",
        "var2": "Domestic and Industrial effluents|Hydrated lime slurry|Sludge|Shear sensitive latex emulsion|Milk curds|Sauces|Fruit juices|Industrial chemicals and detergents|Starch slurries|Coating clays|Gypsum and silicate|Paper stocks|Agricultural slurries",
        "var2n": "Applications",
        "var3": "Available in cast iron or stainless steel, with a choice of rotor and stator materialsA high pressure pump eliminating the need for a series of pumps when pumping over long distances or with high head requirements|Available in standard geometry or extended pitch|Gentle pumping action minimises shear and crush damage|Inspection cover available for applications where rag content is a problem|The pump can be supplied with a square inlet and conveyor to assist viscous slurries into the pumping element|Low running speeds - ideal for abrasive applications",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "27",
        "PD": "0",
        "caption": "Franklin Electrics SR series pumps utilise high grade stainless steel materials for the most demanding applications.",
        "img": "fps_sr.png",
        "range": "FPS-SR",
        "subtitle": "150 mm Stainless Steel Submersible Pumps",
        "title": "\nFPS SR-Series (Replaced by FPS-SS Strap Series)",
        "var1": "150 mm & 200 mm flow rates of up to 120 m³/h.",
        "var1n": "Performance",
        "var2": "Residential|Commercial|Agricultural|Mining|Marine|Municipal|Industrial|River water extraction|DWAF",
        "var2n": "Applications",
        "var3": "Stainless steel impellers and diffusers|Heavy duty stainless steel shell assures permanent alignment of all components to increase longevity and enables higher pressures than strap designs|Teflon® floating wear ring, ceramic bearing journal and|Nitrile rubber fluted bearing ensure durability against wear for long-lasting performance and reliability|Suited to operate in horizontal position|Built-in check valve to protect the pump against water hammer|Energy-efficient hydraulic design for cost-effective operation|Space-saving compact design|Easy to install and dismantle for service in the field if necessary",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    },
    {
        "ID": "28",
        "PD": "0",
        "caption": "Franklin Electrics submersible turbine pumps are designed for use in agricultural, river water extraction, industrial, mining, municipal water supply and DWAF applications.",
        "img": "fps_t.png",
        "range": "FPS-T",
        "subtitle": "150 mm Stainless Steel Submersible Pumps",
        "title": "FPS T-Series (Replaced by FPS-SS Strap Series)",
        "var1": "5”: Heads of up to 120 m and flow rates up to 42 m³/h|6”: Heads of up to 290 m and flow rates up to 132 m³/h|8”: Heads of up to 270 m and flow rates up to 290 m³/h|10”: Heads of up to 170 m and flow rates up to 420 m³/h.",
        "var1n": "Performance",
        "var2": "Residential|Commercial|Agricultural|Mining|Marine|Municipal|Industrial|River water extraction|DWAF",
        "var2n": "Applications",
        "var3": "All fasteners are AISI 304 stainless steel for high quality connection points and easy assembly or dis-assembly|Shaft material - AISI 420 stainless steel for cast iron and AISI 304 stainless steel for bronze pumps|Bearing bushes made from rubber/steel and securely located by press fit|Wear rings made from rubber/steel|Unique high flow pumps on 6” and 8” models|Coupling manufactured from AISI 304 stainless steel|Coupling secured by key and grub-screw|Unique motor adaptor design with improved flow path to protect the motor mechanical seal, shaft end and coupling from high velocity particulates.",
        "var3n": "Features",
        "var4": "",
        "var4n": "",
        "var5": "",
        "var5n": "",
        "variation": ""
    }
]
